### ISSUE TITLE
Crash when falling node is punched

### ISSUE THREAD

**Issue by LoneWolfHT** [octacian/gamemode#3]
If I punch a sand/gravel node the game will crash. Something to do with the hand the gamemode mod registers IIRC. If needed I can post the error

**Comment by octacian** [comment]
b88da3140e637faa3e20d98e4fc454bcdce51aec

Fix info:
> The falling nodes code iterates through and calls
on_dignode callbacks when a falling entities lands
on a node that is not a full block (such as a torch)
and removes it. However, no player is provided to these
callback functions. In order to compensate for this,
whether or not the player variable is defined is first
checked before attempting to call any other gamemode
logic, and if it does not exist, the event is ignored
and allowed to continue as intended.
